<a href="https://colab.research.google.com/github/sys-frOSt/Pytorch_prac/blob/main/training_pipepline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn

In [3]:

df = pd.read_csv(
    "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
)

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2)

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [9]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [10]:
X_train

array([[-1.5523046 , -1.11381224, -1.54629048, ..., -1.75360824,
        -0.51408407, -0.31527528],
       [-0.47499762, -0.65495485, -0.37512387, ...,  0.28296842,
         0.49416836,  1.05530183],
       [ 1.72864963,  1.11492362,  2.13157636, ...,  2.05245305,
         3.9796607 ,  0.84850528],
       ...,
       [-0.35241439,  2.27377262, -0.38954204, ..., -0.76825114,
        -0.86121323, -0.64856972],
       [ 0.24909863,  1.40288004,  0.14763744, ..., -1.31366519,
        -2.13454611, -1.60445376],
       [-1.81200998,  1.24836684, -1.81405632, ..., -1.75360824,
        -0.07386118, -0.76021785]])

In [11]:
X_train_tensor=torch.from_numpy(X_train.astype(np.float32))
X_test_tensor=torch.from_numpy(X_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
      out=self.linear(features)
      out=self.sigmoid(out)
      return out


In [17]:
#loss function
loss_fuction=nn.BCELoss()


In [18]:
learning_rate=0.1
num_epochs=200

In [ ]:
model=Model(X_train_tensor.shape[1])
#start the loop
for epoch in range(num_epochs):
  #initalize the forward pass
  y_pred=model(X_train_tensor)
  #loss calculate
  loss=loss_fuction(y_pred,y_train_tensor.view
  )
  #backpass
  loss.backward()

  #update parameter
  with torch.no_grad():
    model.linear.weight-=learning_rate*model.linear.weight.grad
    model.linear.bias-=learning_rate*model.linear.bias.grad

  #after updating the parameters, the weight will turn into zero for another loop
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #printing the each epoch
  print(f"epoch:{epoch+1},loss:{loss.item()}")

In [26]:
model=Model(X_train_tensor.shape[1])
#optim using
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

#start the loop
for epoch in range(num_epochs):

  #initalize the forward pass
  y_pred=model(X_train_tensor)

  #loss calculate
  loss=loss_fuction(y_pred,y_train_tensor.view(-1,1))

  #clearing gradients
  optimizer.zero_grad()

  #backpass
  loss.backward()

  #update the optimizer using optim
  optimizer.step()

  #printing the each epoch
  print(f"epoch:{epoch+1},loss:{loss.item()}")

epoch:1,loss:0.7805880308151245
epoch:2,loss:0.5638691186904907
epoch:3,loss:0.4562239348888397
epoch:4,loss:0.39367732405662537
epoch:5,loss:0.3521234393119812
epoch:6,loss:0.3220447599887848
epoch:7,loss:0.2989872395992279
epoch:8,loss:0.28057777881622314
epoch:9,loss:0.2654278874397278
epoch:10,loss:0.2526664137840271
epoch:11,loss:0.24171671271324158
epoch:12,loss:0.23218028247356415
epoch:13,loss:0.22377215325832367
epoch:14,loss:0.21628248691558838
epoch:15,loss:0.20955294370651245
epoch:16,loss:0.20346160233020782
epoch:17,loss:0.19791279733181
epoch:18,loss:0.19283024966716766
epoch:19,loss:0.18815238773822784
epoch:20,loss:0.18382874131202698
epoch:21,loss:0.17981745302677155
epoch:22,loss:0.17608359456062317
epoch:23,loss:0.17259757220745087
epoch:24,loss:0.169334277510643
epoch:25,loss:0.16627199947834015
epoch:26,loss:0.16339200735092163
epoch:27,loss:0.16067790985107422
epoch:28,loss:0.1581154316663742
epoch:29,loss:0.15569187700748444
epoch:30,loss:0.15339604020118713
epo

In [79]:
model.linear.bias


Parameter containing:
tensor([-0.1574], requires_grad=True)

In [27]:
#model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5
          ).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy:{accuracy.item()}")


accuracy:0.5236995816230774
